const state={files:[],zoom:1,views:new Set()};
const $=s=>document.querySelector(s);const drop=$('#dropzone'),input=$('#fileInput'),extractor=$('#extractorSelect'),smoothing=$('#smoothingSelect'),button=$('#processButton'),results=$('#results'),empty=$('#empty'),queue=$('#queue');

function addFiles(files){state.files=[...files].filter(f=>f.type.startsWith('image/'));button.disabled=!state.files.length;queue.hidden=!state.files.length;queue.textContent=state.files.length?`${state.files.length} файл(а): ${state.files.map(f=>f.name).join(', ')}`:''}
input.onchange=()=>addFiles(input.files);
for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('drag')});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
const dataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});

button.onclick=async()=>{button.disabled=true;button.textContent='Строю…';empty.hidden=true;const errors=[];for(const file of state.files){queue.textContent=`Обработка: ${file.name}`;try{const original=await dataUrl(file);const response=await fetch('/api/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,extractor:extractor.value,smoothing:smoothing.value,data:original})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Ошибка');addResult(file.name,original,payload)}catch(error){errors.push(`${file.name}: ${error.message}`)}}queue.textContent=errors.length?`⚠ Ошибка — ${errors.join('; ')}`:'Готово';button.disabled=false;button.textContent='Построить примитивы'};

function addResult(name,original,payload){const fragment=$('#resultTemplate').content.cloneNode(true),card=fragment.querySelector('.result-card'),r=payload.report;card.querySelector('h2').textContent=name;card.querySelector('.meta').textContent=`geometry-first · ${r.extractor_used} ${r.analysis_scale}× · ${r.smoothing} · ${r.regions} регионов · ${r.rendered_primitive_count} примитивов`;card.querySelector('[data-view="original"]').src=original;for(const key of ['contour','primitiveMap','rebuilt','corners']){const img=card.querySelector(`[data-view="${key}"]`);if(!img)continue;if(payload.assets[key])img.src=payload.assets[key]+'?t='+Date.now();else img.closest('figure').style.display='none'}card.querySelector('.counts').innerHTML=Object.entries(r.actual).map(([k,v])=>`<span><b>${k}</b> ${v}</span>`).join('')+Object.entries(r.templates).map(([k,v])=>`<span>${k} <b>${v}</b></span>`).join('');results.prepend(card);card.querySelectorAll('.viewport').forEach(setupViewport);applyZoom()}

function setupViewport(view){const img=view.querySelector('img'),v={el:view,img,x:0,y:0,drag:false,lastX:0,lastY:0};state.views.add(v);img.onload=()=>position(v);view.onpointerdown=e=>{v.drag=true;v.lastX=e.clientX;v.lastY=e.clientY;view.setPointerCapture(e.pointerId)};view.onpointermove=e=>{if(!v.drag)return;v.x+=e.clientX-v.lastX;v.y+=e.clientY-v.lastY;v.lastX=e.clientX;v.lastY=e.clientY;position(v)};view.onpointerup=()=>v.drag=false;view.onwheel=e=>{e.preventDefault();setZoom(state.zoom*(e.deltaY<0?1.12:.89))};view.ondblclick=()=>{v.x=v.y=0;setZoom(1)}}
function position(v){v.img.style.transform=`translate(calc(-50% + ${v.x}px),calc(-50% + ${v.y}px)) scale(${state.zoom})`}
function setZoom(value){state.zoom=Math.max(.25,Math.min(8,value));$('#zoomSlider').value=Math.round(state.zoom*100);$('#resetView').textContent=Math.round(state.zoom*100)+'%';applyZoom()}
function applyZoom(){state.views.forEach(position)}$('#zoomSlider').oninput=e=>setZoom(+e.target.value/100);$('#zoomIn').onclick=()=>setZoom(state.zoom*1.25);$('#zoomOut').onclick=()=>setZoom(state.zoom*.8);$('#resetView').onclick=()=>{state.views.forEach(v=>{v.x=v.y=0});setZoom(1)};
