"""Derive objective Experiment-1 annotations from owned source SVGs.

This does not impersonate human review.  A row is admitted as
``ground_truth_derived`` only when the source asset is an owned SVG, its hash is
recorded, and its rendered support aligns with the frozen raster locus under a
conservative bidirectional coverage check.  All failures remain pending.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import time
from typing import Any

import cv2
import numpy as np
from PIL import Image
import resvg_py

from .proposal_real_labels import infer_owned_proposal_family


PROJECT = Path(__file__).resolve().parents[1]
CORPUS = PROJECT / "datasets" / "pcdc_real_loci_v1"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def encode_rle(mask: np.ndarray) -> list[list[int]]:
    flat = mask.astype(bool, copy=False).ravel()
    padded = np.concatenate(
        [np.zeros(1, dtype=np.int8), flat.astype(np.int8), np.zeros(1, dtype=np.int8)]
    )
    changes = np.flatnonzero(np.diff(padded))
    starts = changes[0::2]
    ends = changes[1::2]
    return [[int(start), int(end - start)] for start, end in zip(starts, ends)]


_DISTANCE_THRESHOLDS = (4, 8, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96, 128, 160, 192)


def _read_source_rgba(path: Path) -> np.ndarray:
    with Image.open(path) as image:
        return np.asarray(image.convert("RGBA"), dtype=np.uint8)


def _background_candidates(rgb: np.ndarray) -> list[tuple[str, np.ndarray]]:
    """Return robust background hypotheses without assuming empty borders.

    Text and logos in the challenge corpus often touch every image edge, so a
    border median alone can be an object colour.  Dominant quantised colours
    give independent hypotheses for white/solid backgrounds.  The later
    bidirectional support check, not this heuristic, decides whether any
    hypothesis is admissible.
    """

    rgb_i16 = rgb.astype(np.int16)
    border = np.concatenate(
        (rgb_i16[0], rgb_i16[-1], rgb_i16[:, 0], rgb_i16[:, -1]), axis=0
    )
    corners = np.asarray(
        (rgb_i16[0, 0], rgb_i16[0, -1], rgb_i16[-1, 0], rgb_i16[-1, -1])
    )
    candidates: list[tuple[str, np.ndarray]] = [
        ("border_median", np.median(border, axis=0)),
        ("corner_median", np.median(corners, axis=0)),
    ]

    quantised = (rgb // 16).astype(np.int32)
    keys = quantised[..., 0] * 256 + quantised[..., 1] * 16 + quantised[..., 2]
    values, counts = np.unique(keys, return_counts=True)
    for rank, key in enumerate(values[np.argsort(counts)[-4:][::-1]]):
        pixels = rgb_i16[keys == key]
        candidates.append((f"dominant_colour_{rank}", np.median(pixels, axis=0)))

    unique: list[tuple[str, np.ndarray]] = []
    seen: set[tuple[int, int, int]] = set()
    for name, colour in candidates:
        signature = tuple(int(round(value)) for value in colour)
        if signature not in seen:
            unique.append((name, colour))
            seen.add(signature)
    return unique


def _source_foreground_candidates(
    rgba: np.ndarray,
) -> list[tuple[str, np.ndarray]]:
    alpha = rgba[..., 3]
    if int(alpha.max()) - int(alpha.min()) > 8:
        return [("source_alpha_gt_4", alpha > 4)]

    rgb = rgba[..., :3]
    rgb_i16 = rgb.astype(np.int16)
    candidates: list[tuple[str, np.ndarray]] = []
    for background_name, background in _background_candidates(rgb):
        distance = np.max(np.abs(rgb_i16 - background), axis=2)
        candidates.extend(
            (
                f"{background_name}:linf_gt_{threshold}",
                distance > threshold,
            )
            for threshold in _DISTANCE_THRESHOLDS
        )
    return candidates


def _render_svg_rgba(
    path: Path, width: int, height: int
) -> tuple[np.ndarray, str]:
    """Render without aspect-ratio distortion and require exact raster size.

    ``resvg`` treats simultaneous width/height as a containing box.  A nominal
    482x160 SVG can therefore become 482x161.  Challenge-pack rasters were
    generated by target height, so height-only is the canonical first attempt;
    width-only and the containing box are exact-size fallbacks.
    """

    svg = path.read_text(encoding="utf-8", errors="strict")
    attempts = (
        ("height_only", {"height": height}),
        ("width_only", {"width": width}),
        ("width_height_box", {"width": width, "height": height}),
    )
    observed: list[str] = []
    for mode, options in attempts:
        rendered = resvg_py.svg_to_bytes(svg_string=svg, **options)
        with Image.open(io.BytesIO(bytes(rendered))) as image:
            rgba = np.asarray(image.convert("RGBA"), dtype=np.uint8)
        observed.append(f"{mode}={rgba.shape[1]}x{rgba.shape[0]}")
        if rgba.shape[:2] == (height, width):
            return rgba, mode
    raise ValueError(
        f"no exact-size SVG render for {width}x{height}; " + ", ".join(observed)
    )


def _alignment(source: np.ndarray, gt: np.ndarray) -> dict[str, float]:
    kernel = np.ones((3, 3), np.uint8)
    source_dilated = cv2.dilate(source.astype(np.uint8), kernel) > 0
    gt_dilated = cv2.dilate(gt.astype(np.uint8), kernel) > 0
    source_covered = float(np.sum(source & gt_dilated) / max(1, source.sum()))
    gt_covered = float(np.sum(gt & source_dilated) / max(1, gt.sum()))
    union = int(np.sum(source | gt))
    iou = float(np.sum(source & gt) / max(1, union))
    return {
        "source_covered_1px": source_covered,
        "gt_covered_1px": gt_covered,
        "iou": iou,
        "minimum_coverage": min(source_covered, gt_covered),
    }


def _best_support_alignment(
    source_rgba: np.ndarray, gt: np.ndarray
) -> tuple[np.ndarray, dict[str, Any]]:
    best: tuple[tuple[float, float], np.ndarray, dict[str, Any]] | None = None
    for method, source in _source_foreground_candidates(source_rgba):
        alignment = _alignment(source, gt)
        score = (alignment["minimum_coverage"], alignment["iou"])
        details: dict[str, Any] = {
            **alignment,
            "source_mask_method": method,
            "source_support_fraction": float(source.mean()),
            "gt_support_fraction": float(gt.mean()),
        }
        if best is None or score > best[0]:
            best = (score, source, details)
    if best is None:
        raise ValueError("no source support hypotheses")
    return best[1], best[2]


def _opaque_design_support(
    source_rgba: np.ndarray, gt_rgba: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    """Recover foreground support when an SVG paints an opaque background.

    Alpha is semantic evidence only when it varies.  For an opaque text/logo
    canvas it describes the background rectangle as well, so using alpha would
    turn the whole image into one fake glyph.  The owned SVG render supplies a
    noise-free background/foreground separation; the frozen raster is used
    independently for the bidirectional alignment proof.
    """
    gt_rgb = gt_rgba[..., :3]
    gt_i16 = gt_rgb.astype(np.int16)
    best: tuple[
        tuple[float, float, float], np.ndarray, np.ndarray, dict[str, Any]
    ] | None = None
    for background_name, background in _background_candidates(gt_rgb):
        distance = np.max(np.abs(gt_i16 - background), axis=2)
        support = distance > 4
        topology = distance >= 64
        fraction = float(support.mean())
        if not np.any(support) or not np.any(topology) or fraction >= 0.65:
            continue
        _source_mask, alignment = _best_support_alignment(source_rgba, support)
        details: dict[str, Any] = {
            **alignment,
            "gt_mask_method": f"{background_name}:opaque_rgb_linf_gt_4",
            "gt_topology_method": f"{background_name}:opaque_rgb_linf_ge_64",
            "gt_background_rgb": [float(value) for value in background],
            "gt_support_fraction": fraction,
        }
        # Coverage is decisive.  Equal exact-render hypotheses prefer the
        # smaller foreground, i.e. the dominant/background interpretation.
        score = (
            float(alignment["minimum_coverage"]),
            float(alignment["iou"]), -fraction,
        )
        if best is None or score > best[0]:
            best = (score, support, topology, details)
    if best is None:
        raise ValueError("opaque SVG has no defensible foreground/background split")
    return best[1], best[2], best[3]


def _photometric_alignment(source_rgb: np.ndarray, gt_rgb: np.ndarray) -> dict[str, float]:
    """Measure exact-source agreement for SVGs whose alpha fills the canvas."""

    source = source_rgb.astype(np.float32)
    gt = gt_rgb.astype(np.float32)
    mae = float(np.mean(np.abs(source - gt)))

    source_gray = cv2.cvtColor(source, cv2.COLOR_RGB2GRAY)
    gt_gray = cv2.cvtColor(gt, cv2.COLOR_RGB2GRAY)
    c1 = (0.01 * 255.0) ** 2
    c2 = (0.03 * 255.0) ** 2
    mu_source = cv2.GaussianBlur(source_gray, (11, 11), 1.5)
    mu_gt = cv2.GaussianBlur(gt_gray, (11, 11), 1.5)
    mu_source_sq = mu_source * mu_source
    mu_gt_sq = mu_gt * mu_gt
    mu_product = mu_source * mu_gt
    sigma_source = cv2.GaussianBlur(source_gray * source_gray, (11, 11), 1.5) - mu_source_sq
    sigma_gt = cv2.GaussianBlur(gt_gray * gt_gray, (11, 11), 1.5) - mu_gt_sq
    covariance = cv2.GaussianBlur(source_gray * gt_gray, (11, 11), 1.5) - mu_product
    numerator = (2.0 * mu_product + c1) * (2.0 * covariance + c2)
    denominator = (mu_source_sq + mu_gt_sq + c1) * (sigma_source + sigma_gt + c2)
    ssim = float(np.mean(numerator / np.maximum(denominator, 1e-12)))
    return {"rgb_mae_255": mae, "grayscale_ssim": ssim}


def _topology(mask: np.ndarray) -> tuple[int, int]:
    contours, hierarchy = cv2.findContours(
        mask.astype(np.uint8), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE
    )
    if hierarchy is None:
        return 0, 0
    parents = hierarchy[0, :, 3]
    return int(np.sum(parents < 0)), int(np.sum(parents >= 0))


def _bbox(mask: np.ndarray) -> list[int]:
    ys, xs = np.nonzero(mask)
    if not len(xs):
        return [0, 0, mask.shape[1], mask.shape[0]]
    return [int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1]


def _layer_relation(svg: str, semantic_class: str) -> str:
    lowered = svg.lower()
    if "<mask" in lowered or "mask=" in lowered:
        return "knockout"
    if "<clippath" in lowered or "clip-path=" in lowered:
        return "overlap"
    if re.search(r"(?:opacity|fill-opacity|stroke-opacity)\s*=\s*['\"](?:0?\.[0-9]+)", lowered):
        return "overlap"
    return "unknown" if semantic_class == "layer_knockout" else "none"


def derive(
    corpus_dir: Path = CORPUS,
    *,
    minimum_coverage: float = 0.90,
) -> dict[str, Any]:
    manifest = json.loads((corpus_dir / "manifest.json").read_text("utf-8"))
    review_path = corpus_dir / "review.json"
    review_payload = json.loads(review_path.read_text("utf-8"))
    reviews = review_payload.setdefault("reviews", {})
    derived = 0
    rejected: list[dict[str, Any]] = []
    skipped = 0
    for locus in manifest["loci"]:
        existing = reviews.get(locus["id"])
        if existing and existing.get("status") in {"evidence_reviewed", "complete"}:
            skipped += 1
            continue
        source_asset_value = locus["source"].get("source_asset")
        asset = Path(source_asset_value) if source_asset_value else None
        if asset is None or asset.suffix.lower() != ".svg" or not asset.is_file():
            if existing and existing.get("status") == "ground_truth_derived":
                reviews.pop(locus["id"], None)
            skipped += 1
            continue
        try:
            width = int(locus["image"]["width"])
            height = int(locus["image"]["height"])
            source_rgba = _read_source_rgba(Path(locus["source"]["path"]))
            gt_rgba, render_mode = _render_svg_rgba(asset, width, height)
            gt_mask = gt_rgba[..., 3] > 4
            full_canvas = float(gt_mask.mean()) >= 0.995
            topology_mask = gt_rgba[..., 3] >= 128
            photometric: dict[str, float] | None = None
            if full_canvas:
                photometric = _photometric_alignment(
                    source_rgba[..., :3], gt_rgba[..., :3]
                )
                alignment: dict[str, Any] = {
                    "minimum_coverage": 1.0,
                    "source_covered_1px": 1.0,
                    "gt_covered_1px": 1.0,
                    "iou": 1.0,
                    "source_mask_method": "opaque_canvas_photometric_proof",
                    "source_support_fraction": float(
                        np.mean(source_rgba[..., 3] > 250)
                    ),
                    "gt_support_fraction": float(gt_mask.mean()),
                }
                photometric_pass = (
                    alignment["source_support_fraction"] >= 0.995
                    and photometric["rgb_mae_255"] <= 12.0
                    and photometric["grayscale_ssim"] >= 0.80
                )
                if not photometric_pass:
                    rejected.append({
                        "id": locus["id"],
                        "reason": "full_canvas_photometric_alignment",
                        "alignment": alignment,
                        "photometric": photometric,
                    })
                    if existing and existing.get("status") == "ground_truth_derived":
                        reviews.pop(locus["id"], None)
                    continue
                if locus["semantic_class"] == "text":
                    gt_mask, topology_mask, opaque_alignment = _opaque_design_support(
                        source_rgba, gt_rgba
                    )
                    alignment = {
                        **opaque_alignment,
                        "photometric_canvas_proof": True,
                    }
            else:
                _source_mask, alignment = _best_support_alignment(
                    source_rgba, gt_mask
                )
            # Demand bidirectional one-pixel coverage so a wrong rendition
            # cannot be blessed merely because one mask contains the other.
            support_alignment_required = (
                not full_canvas or locus["semantic_class"] == "text"
            )
            if (
                support_alignment_required
                and alignment["minimum_coverage"] < minimum_coverage
            ):
                rejected.append({
                    "id": locus["id"], "reason": "support_alignment",
                    "alignment": alignment,
                })
                if existing and existing.get("status") == "ground_truth_derived":
                    reviews.pop(locus["id"], None)
                continue
            # Design topology must not count low-alpha rasterizer fringes as
            # holes/components.  Support remains conservative at alpha>4,
            # while topology is measured at the SVG coverage midline.
            components, holes = _topology(topology_mask)
            if not gt_mask.any() or components <= 0:
                rejected.append({"id": locus["id"], "reason": "empty_gt_support"})
                continue
            svg_text = asset.read_text(encoding="utf-8", errors="replace")
            derived_review = {
                "status": "ground_truth_derived",
                "roi_xyxy": _bbox(gt_mask),
                "acceptable_support": (
                    "Owned source SVG opaque-RGB foreground support"
                    if full_canvas and locus["semantic_class"] == "text"
                    else "Owned source SVG alpha support"
                ),
                "support_rle": encode_rle(gt_mask),
                "support_area": int(gt_mask.sum()),
                "support_size": [width, height],
                "topology_rle": encode_rle(topology_mask),
                "topology_area": int(topology_mask.sum()),
                "topology_support": (
                    "Owned opaque SVG RGB distance midline"
                    if full_canvas and locus["semantic_class"] == "text"
                    else "Owned SVG alpha coverage midline"
                ),
                "components": components,
                "holes": holes,
                "macro_family": locus["semantic_class"],
                "text_line_membership": (
                    "yes" if locus["semantic_class"] == "text" else "not_applicable"
                ),
                "layer_relation": _layer_relation(
                    svg_text, locus["semantic_class"]
                ),
                "preferred_candidate": "",
                "notes": "Objective GT-derived evidence; human candidate preference still pending.",
                "reviewer": "owned-svg-ground-truth-adapter/v4",
                "updated_at": time.time(),
                "provenance": {
                    "kind": "ground_truth_derived",
                    "source_asset": str(asset.resolve()),
                    "source_asset_sha256": _sha256(asset),
                    "renderer": "resvg_py",
                    "renderer_mode": render_mode,
                    "alignment": alignment,
                    "photometric": photometric,
                    "minimum_coverage_gate": minimum_coverage,
                    "topology_alpha_threshold": (
                        None if full_canvas and locus["semantic_class"] == "text"
                        else 128
                    ),
                    "adapter": "owned-svg-ground-truth-adapter/v4",
                },
            }
            proposal_family, proposal_provenance = infer_owned_proposal_family(
                locus, derived_review,
            )
            if proposal_family is not None:
                derived_review["proposal_family"] = proposal_family
                derived_review["proposal_family_provenance"] = proposal_provenance
            reviews[locus["id"]] = derived_review
            derived += 1
        except Exception as exc:
            if existing and existing.get("status") == "ground_truth_derived":
                reviews.pop(locus["id"], None)
            rejected.append({
                "id": locus["id"],
                "reason": f"{type(exc).__name__}: {exc}"[:500],
            })
    review_payload["updated_at"] = time.time()
    review_payload["ground_truth_derived_count"] = sum(
        review.get("status") == "ground_truth_derived"
        for review in reviews.values()
    )
    review_payload["evidence_reviewed_count"] = sum(
        review.get("status") in {
            "ground_truth_derived", "evidence_reviewed", "complete"
        }
        for review in reviews.values()
    )
    review_payload["complete_count"] = sum(
        review.get("status") == "complete" for review in reviews.values()
    )
    temporary = review_path.with_suffix(".json.tmp")
    temporary.write_text(
        json.dumps(review_payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(review_path)
    report = {
        "schema": "pcdc-locus-gt-derivation/v1",
        "minimum_coverage": minimum_coverage,
        "derived_this_run": derived,
        "derived_total": review_payload["ground_truth_derived_count"],
        "evidence_reviewed_total": review_payload["evidence_reviewed_count"],
        "skipped": skipped,
        "rejected_count": len(rejected),
        "rejected": rejected,
    }
    report_path = corpus_dir / "gt_derivation_report.json"
    report_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", type=Path, default=CORPUS)
    parser.add_argument("--minimum-coverage", type=float, default=0.90)
    args = parser.parse_args()
    report = derive(args.corpus, minimum_coverage=args.minimum_coverage)
    print(json.dumps({
        key: report[key] for key in (
            "minimum_coverage", "derived_this_run", "derived_total",
            "evidence_reviewed_total", "skipped", "rejected_count"
        )
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
